# Generated by Django 3.2.9 on 2021-11-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('contributor', models.CharField(max_length=20)),
                ('good', models.IntegerField()),
                ('priority', models.CharField(choices=[('primary', 'high'),
                                                       ('primary', 'normal'),
                                                       ('primary', 'low')],
                                              max_length=10)),
            ],
        ),
    ]
