# Generated by Django 3.2.9 on 2021-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boadmodel',
            name='good',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
