# Generated by Django 3.2.9 on 2021-11-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_alter_boadmodel_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='boadmodel',
            name='follow',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
