# Generated by Django 3.2.9 on 2021-11-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_boadmodel_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boadmodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'),
                                            ('success', 'normal'),
                                            ('primary', 'low')],
                                   max_length=10),
        ),
    ]
